<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , aswift_3, , ))_aswift_3</name>
   <tag></tag>
   <elementGuidId>2e5efe1b-d81c-4810-9336-86d9ba02c88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aswift_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='aswift_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;aswift_3&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3067ed82-c79f-4680-9ea0-fa2c687b546d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aswift_3</value>
      <webElementGuid>ca5cacca-f04e-4171-84d1-e5daee9202f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aswift_3</value>
      <webElementGuid>13cc5510-8123-464a-a100-92e327f79bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>eed4f913-43f3-4726-b437-9e78e4769c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ebdcf248-8d32-4f84-939b-c0925f77e8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a7498f8-769c-48a4-8908-7e8ca8b4197a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0712c330-71c7-4585-8589-b33f4ef84c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9abf8c68-cf29-480c-962b-c6035314ca98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3da1d9c3-e633-41cc-a479-1e71f25285af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>490aae53-4c5d-4384-bf41-3b463b4d80b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>96db2392-6023-4dc5-a0fc-4c0f50927179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://googleads.g.doubleclick.net/pagead/html/r20240429/r20110914/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-1677597403311019&amp;fa=8&amp;ifi=4&amp;uci=a!4</value>
      <webElementGuid>dae1a8bf-5c00-4110-a3e8-b5b53684c9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>a!4</value>
      <webElementGuid>6fb00ecd-fbd6-4d7f-a0d9-b50059cf0357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f8e1a52-ca47-4de6-99a7-e992e1ee8ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>bb53a510-43b1-488f-8335-f4e1fc45ee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>281ffc77-3500-40a5-b229-7194f015bd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-query-id</name>
      <type>Main</type>
      <value>CIW195Lw7IUDFVXmTAIdL-MKQQ</value>
      <webElementGuid>6121d816-adf5-4b29-9152-1bc1d82c6313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>65f6bd18-5008-45ea-8612-dfda8d213955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aswift_3&quot;)</value>
      <webElementGuid>dea6c77e-0598-4ec6-bb96-996da3ae481a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='aswift_3']</value>
      <webElementGuid>69af0d19-0dce-4b6b-b445-09e7aede1db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aswift_3_host']/iframe</value>
      <webElementGuid>8bb16b78-89b9-4cf8-9f70-594e832feb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//html/ins/div/iframe</value>
      <webElementGuid>55b6f7b9-b764-477f-a8c1-3318350cb84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'aswift_3' and @name = 'aswift_3' and @src = 'https://googleads.g.doubleclick.net/pagead/html/r20240429/r20110914/zrt_lookup_fy2021.html#RS-0-&amp;adk=1812271808&amp;client=ca-pub-1677597403311019&amp;fa=8&amp;ifi=4&amp;uci=a!4' and @title = 'Advertisement']</value>
      <webElementGuid>2735b1b7-9ce2-4ce2-8ef5-1ca93d3e65e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
