<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your product has been added to cart</name>
   <tag></tag>
   <elementGuidId>0ce8ff5d-4c2d-4656-b644-3346f03ef694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cartModal']/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Your product has been added to cart.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ecaf6d18-2ddc-47b5-b4c8-6708bbd93a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>c4f153e8-16dc-45e9-866a-9a8944bd530b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your product has been added to cart.</value>
      <webElementGuid>094a714d-4091-47d0-971c-60a8fef81acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartModal&quot;)/div[@class=&quot;modal-dialog modal-confirm&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/p[@class=&quot;text-center&quot;]</value>
      <webElementGuid>cc9ebc68-749d-4999-8c68-f88d6d8c7166</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cartModal']/div/div/div[2]/p</value>
      <webElementGuid>f315525c-fd8b-4d92-b75a-dad0c05291d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added!'])[1]/following::p[1]</value>
      <webElementGuid>2d5dda1f-9e6e-4e85-b7a0-0acc3e839704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::p[1]</value>
      <webElementGuid>7f481987-6561-40a9-981a-c8f7b0a3cb3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Cart'])[1]/preceding::p[1]</value>
      <webElementGuid>eef9c5ac-7644-47ad-9c45-0fc236d1c71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/preceding::p[2]</value>
      <webElementGuid>201f7e6f-a62a-4fcb-9b76-4d812584fb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your product has been added to cart.']/parent::*</value>
      <webElementGuid>199c5b92-afa8-4485-aa82-89025914ce6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>15bf26a6-dca3-4697-8de0-733c4727fe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your product has been added to cart.' or . = 'Your product has been added to cart.')]</value>
      <webElementGuid>8aaf39ab-aae7-43d7-b56c-836ad96cb4af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
