<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Write Your Review_review</name>
   <tag></tag>
   <elementGuidId>eeba41c9-7208-40bd-bc16-c99d9c27e03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Add Review Here!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5b4b73ea-95e3-4b94-95df-66b5baa76c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>review</value>
      <webElementGuid>b5c7bea4-93b2-4213-8dd4-3c6822ef24aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Review Here!</value>
      <webElementGuid>732eeb76-a7ee-4d08-89e8-4fc5804428f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>review</value>
      <webElementGuid>6417543d-66a3-4d76-89d4-016501fd0b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review&quot;)</value>
      <webElementGuid>74d7bc49-27d6-4dde-8650-3b2ffaec3aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='review']</value>
      <webElementGuid>aa861951-d1ad-4bc7-a878-9820a45bcaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='review-form']/textarea</value>
      <webElementGuid>ba3f3011-d4d6-4e67-9acd-e3c45d335ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d5784cd1-ff4d-4748-a6db-013302e9412b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'review' and @placeholder = 'Add Review Here!' and @id = 'review']</value>
      <webElementGuid>17fd6198-a777-434a-b197-9eed86f15f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
