<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact us_search</name>
   <tag></tag>
   <elementGuidId>ef476abb-689f-42fa-b7f1-d07299f46929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_product']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search Product&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b775a328-e35f-47a3-9ea4-2994203ce912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ca7ab9e-5e77-4e26-9cbb-ea513d8f9201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e88841a8-d43e-49d3-8a8e-112668400913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_product</value>
      <webElementGuid>c6faa64b-97d9-49e3-ad5c-be2c668af90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Product</value>
      <webElementGuid>57e26676-5b15-478f-9628-686b346a8225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>e95929a8-cc79-47d7-9a52-ee716f13909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_product&quot;)</value>
      <webElementGuid>84a07071-9937-47ac-a3f8-42ea37db551c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_product']</value>
      <webElementGuid>c6a36d1f-9cc9-4016-abb6-6487670c6631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='advertisement']/div/input</value>
      <webElementGuid>bf96249e-be22-4fad-b6ef-4754842db80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9e1c59ea-ea97-4161-b811-e2bd7c7866ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search' and @id = 'search_product' and @placeholder = 'Search Product']</value>
      <webElementGuid>72726e55-9da6-42b7-827a-eb55e3c6f9f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
